apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-schema
  namespace: ebs
data:
  schema.sql: |
    CREATE DATABASE IF NOT EXISTS ebs;
    USE ebs;

    CREATE TABLE IF NOT EXISTS users (
      id CHAR(36) PRIMARY KEY,
      name VARCHAR(120) NOT NULL,
      email VARCHAR(190) NOT NULL UNIQUE,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS events (
      id CHAR(36) PRIMARY KEY,
      title VARCHAR(200) NOT NULL,
      total_seats INT NOT NULL,
      available_seats INT NOT NULL,
      event_date DATETIME NOT NULL,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS bookings (
      id CHAR(36) PRIMARY KEY,
      user_id CHAR(36) NOT NULL,
      event_id CHAR(36) NOT NULL,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      INDEX idx_event(event_id),
      INDEX idx_user(user_id)
    );

    CREATE TABLE IF NOT EXISTS notification_logs (
      id BIGINT AUTO_INCREMENT PRIMARY KEY,
      booking_id CHAR(36) NOT NULL,
      user_id CHAR(36) NOT NULL,
      event_id CHAR(36) NOT NULL,
      message VARCHAR(255) NOT NULL,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: ebs
spec:
  replicas: 1
  selector:
    matchLabels: { app: mysql }
  template:
    metadata:
      labels: { app: mysql }
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MYSQL_DB
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: initdb
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: initdb
          configMap:
            name: mysql-schema
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: ebs
spec:
  selector: { app: mysql }
  ports:
    - port: 3306
      targetPort: 3306
