apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-service
  namespace: ebs
spec:
  replicas: 1
  selector:
    matchLabels: { app: event-service }
  template:
    metadata:
      labels: { app: event-service }
    spec:
      containers:
        - name: event-service
          image: event-service:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
          env:
            - { name: CACHE_TTL, value: "60" }
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: event-service
  namespace: ebs
spec:
  selector: { app: event-service }
  ports:
    - port: 3000
      targetPort: 3000
