apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service
  namespace: ebs
spec:
  replicas: 1
  selector:
    matchLabels: { app: booking-service }
  template:
    metadata:
      labels: { app: booking-service }
    spec:
      containers:
        - name: booking-service
          image: booking-service:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: booking-service
  namespace: ebs
spec:
  selector: { app: booking-service }
  ports:
    - port: 3000
      targetPort: 3000
